// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO refresh_tokens (token, user_id, expires_at, created_at, updated_at, revoked_at)
VALUES (
    $1,
    $2,
    $3,
    NOW(),
    NOW(),
    NULL
)
`

type AddRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, addRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}

const validateRefreshToken = `-- name: ValidateRefreshToken :one
SELECT users.id, users.email
FROM refresh_tokens
JOIN users on users.id = refresh_tokens.user_id
WHERE refresh_tokens.token = $1
AND refresh_tokens.expires_at > NOW()
AND refresh_tokens.revoked_at IS NULL
`

type ValidateRefreshTokenRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) ValidateRefreshToken(ctx context.Context, token string) (ValidateRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, validateRefreshToken, token)
	var i ValidateRefreshTokenRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
